language: node_js
node_js:
- '4.0'
- '7.0'
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: gozKbjN5y764ibdpiEa8YlzmQseSjR4kQdGvYoB2MHWLrJ1dKe7yGEn/Dgd5DpzqFapPEy5NjSNDOSZwkq8QuRnzlw3F5iqPClRR9ly4lmgpWOfDGJFKWnwvnAo+jaedqOIrm8lXASC9TB/ltXvpFzQ3EJQ2WngeOmNKeTUclyE=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: STI8hV1ZawQtuKM/ZBwsuz8ciP9QsK7b4797NnNM05Dq2cPA2rMzwGk1VIZIGGRlt22tPHXhMod3kBscqgkknHT409xs2DGWDJsY5QJFDXYau6vY1BgvGftokZwE1KG90uK2zAjitaNElD6Hl/YLc1JVZlBNKkseXxE2jjOUkOU=
    file:
      - "retext-pos.js"
      - "retext-pos.min.js"
    on:
      tags: true
      node: '7.0'
